site_name: wtf - Terminal AI Assistant
site_url: https://davefowler.github.io/wtf-terminal-ai/
site_description: A command-line AI assistant that provides contextual help based on terminal history
site_author: wtf contributors
repo_url: https://github.com/davefowler/wtf-terminal-ai
repo_name: davefowler/wtf-terminal-ai

theme:
  name: material
  palette:
    # Light mode - terminal style
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode - classic terminal (black background, green text)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'IBM Plex Mono'
    code: 'IBM Plex Mono'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started.md
      - Setup: setup.md
      - Quick Tour: quick-tour.md
  - Properties:
      - Memories: properties/memories.md
      - Keys: properties/keys.md
      - Personality: properties/personality.md
      - Hooks: properties/hooks.md
  - Configuration:
      - Overview: config/files.md
      - Web Search: config/web-search.md
      - Allowlist: config/allowlist.md
  - Reference:
      - CLI Options: reference/cli-options.md
      - FAQ: faq.md
      - Troubleshooting: troubleshooting.md
      - Comparison: comparison.md
  - About:
      - Acknowledgments: acknowledgments.md
      - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/davefowler/wtf-terminal-ai

extra_css:
  - stylesheets/terminal.css
